name = "deutsch"
version = "0.1.0"
defaultTargets = ["Deutsch", "DeutschErrata", "DeutschTests", "DeutschErrataTests"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "Deutsch"

[[lean_lib]]
name = "DeutschTests"

[[lean_lib]]
name = "DeutschErrata"

[[lean_lib]]
name = "DeutschErrataTests"
