import Deutsch.Descriptor.Basic
import Mathlib.Algebra.Star.UnitaryStarAlgAut
import Mathlib.Data.Finset.NoncommProd
import Mathlib.LinearAlgebra.Matrix.Permutation
import Mathlib.LinearAlgebra.Matrix.StdBasis
import Mathlib.RingTheory.Adjoin.Basic

/-!
# Algebraic completeness of the initial descriptor family

The embedded initial `X` and `Z` descriptor components generate the full complex matrix algebra on
an arbitrary finite named register.  The proof is constructive: `Z`-derived coordinate projectors
isolate computational-basis states, commuting `X` factors implement the required basis transition,
and sandwiching that transition between two projectors reconstructs every standard matrix unit.

`Finset.noncommProd` records the pairwise commutation of coordinate factors, so no ordering or
nonemptiness assumption is imposed on the register labels.
-/

namespace Deutsch
namespace DescriptorFamily

open Register

noncomputable section

/-- The set of every axis component occurring in a descriptor family. -/
def components {Q : Type*} [Fintype Q] [DecidableEq Q]
    (D : DescriptorFamily Q) : Set (Operator Q) :=
  Set.range fun qa : Q × Axis => (D qa.1).component qa.2

/-- A descriptor family is algebraically complete when its components generate every operator. -/
def GeneratesOperatorAlgebra {Q : Type*} [Fintype Q] [DecidableEq Q]
    (D : DescriptorFamily Q) : Prop :=
  Algebra.adjoin ℂ (components D) = ⊤

/-- The initial `X` and `Z` descriptor components, a sufficient generating subfamily. -/
def initialXZComponents (Q : Type*) [Fintype Q] [DecidableEq Q] : Set (Operator Q) :=
  Set.range (fun q => (initial Q q).component .x) ∪
    Set.range (fun q => (initial Q q).component .z)

/-- Every component of every initial descriptor triple. -/
def initialComponents (Q : Type*) [Fintype Q] [DecidableEq Q] : Set (Operator Q) :=
  components (initial Q)

/-- The sufficient descriptor subfamily is exactly the embedded `X`/`Z` range union. -/
theorem initialXZComponents_eq_xAt_zAt {Q : Type*} [Fintype Q] [DecidableEq Q] :
    initialXZComponents Q =
      Set.range (Register.xAt : Q → Operator Q) ∪ Set.range Register.zAt := by
  rfl

/-- The sufficient `X`/`Z` subfamily is contained in the full initial descriptor family. -/
theorem initialXZComponents_subset_initialComponents {Q : Type*}
    [Fintype Q] [DecidableEq Q] :
    initialXZComponents Q ⊆ initialComponents Q := by
  rintro A (⟨q, rfl⟩ | ⟨q, rfl⟩)
  · exact ⟨(q, .x), rfl⟩
  · exact ⟨(q, .z), rfl⟩

end

namespace Generation

open Foundations Register
open scoped Matrix

noncomputable section

variable {Q : Type*} [Fintype Q] [DecidableEq Q]

/-- The operator subalgebra generated by the sufficient initial descriptor components. -/
def generated : Subalgebra ℂ (Operator Q) :=
  Algebra.adjoin ℂ (initialXZComponents Q)

theorem xAt_mem_generated (q : Q) : xAt q ∈ generated (Q := Q) :=
  Algebra.subset_adjoin (Set.mem_union_left _ (Set.mem_range_self q))

theorem zAt_mem_generated (q : Q) : zAt q ∈ generated (Q := Q) :=
  Algebra.subset_adjoin (Set.mem_union_right _ (Set.mem_range_self q))

/-- Flip the raw computational bit at one named register coordinate. -/
def flipAt (q : Q) : Equiv.Perm (Basis Q) where
  toFun x r := if r = q then Equiv.swap (0 : QubitIndex) 1 (x r) else x r
  invFun x r := if r = q then Equiv.swap (0 : QubitIndex) 1 (x r) else x r
  left_inv x := by
    funext r
    by_cases hr : r = q
    · simp [hr]
    · simp [hr]
  right_inv x := by
    funext r
    by_cases hr : r = q
    · simp [hr]
    · simp [hr]

omit [Fintype Q] in
@[simp]
theorem flipAt_apply_same (q : Q) (x : Basis Q) :
    flipAt q x q = Equiv.swap (0 : QubitIndex) 1 (x q) := by
  simp [flipAt]

omit [Fintype Q] in
@[simp]
theorem flipAt_apply_of_ne {q r : Q} (h : r ≠ q) (x : Basis Q) :
    flipAt q x r = x r := by
  simp [flipAt, h]

omit [Fintype Q] in
theorem flipAt_inv (q : Q) : (flipAt q)⁻¹ = flipAt q := by
  ext x r
  rfl

omit [Fintype Q] in
theorem flipAt_commute_of_ne {q r : Q} (hqr : q ≠ r) :
    Commute (flipAt q) (flipAt r) := by
  rw [commute_iff_eq]
  ext x t
  simp only [Equiv.Perm.mul_apply]
  by_cases htq : t = q
  · subst t
    simp [flipAt, hqr]
  · by_cases htr : t = r
    · subst t
      simp [flipAt, hqr.symm]
    · simp [flipAt, htq, htr]

/-- The embedded Pauli `X` is exactly the permutation matrix of a coordinate bit flip. -/
theorem xAt_eq_permMatrix (q : Q) :
    xAt q = (flipAt q).permMatrix ℂ := by
  ext a b
  rw [xAt, embedQubit_apply_ite]
  by_cases hout : ∀ j, j ≠ q → a j = b j
  · rw [if_pos hout]
    simp only [Equiv.Perm.permMatrix, PEquiv.toMatrix_apply,
      Equiv.toPEquiv_apply, Option.mem_def, Option.some.injEq]
    have hab : flipAt q a = b ↔ flipAt q a q = b q := by
      constructor
      · intro h
        exact congr_fun h q
      · intro hq
        funext r
        by_cases hr : r = q
        · subst r
          exact hq
        · rw [flipAt_apply_of_ne hr]
          exact hout r hr
    simp only [hab]
    generalize ha : a q = aq
    generalize hb : b q = bq
    fin_cases aq <;> fin_cases bq <;>
      simp_all [pauliX, flipAt]
  · rw [if_neg hout]
    simp only [Equiv.Perm.permMatrix, PEquiv.toMatrix_apply,
      Equiv.toPEquiv_apply, Option.mem_def, Option.some.injEq]
    rw [if_neg]
    intro hba
    apply hout
    intro r hr
    rw [← hba, flipAt_apply_of_ne hr]

/-- The logical-paper-bit-`1` projector is diagonal in the register basis. -/
theorem paperBitOneProjectorAt_eq_diagonal (q : Q) :
    paperBitOneProjectorAt q =
      Matrix.diagonal (fun x : Basis Q => if x q = 0 then (1 : ℂ) else 0) := by
  ext a b
  rw [paperBitOneProjectorAt, embedQubit_apply_ite]
  by_cases hab : a = b
  · subst b
    rw [if_pos (fun _ _ ↦ rfl)]
    simp only [Matrix.diagonal_apply_eq]
    rw [bitOneProjector_explicit]
    generalize ha : a q = aq
    fin_cases aq <;> simp_all
  · rw [Matrix.diagonal_apply_ne _ hab]
    by_cases hout : ∀ j, j ≠ q → a j = b j
    · rw [if_pos hout, bitOneProjector_explicit]
      have hq : a q ≠ b q := by
        intro h
        apply hab
        funext r
        by_cases hr : r = q
        · subst r
          exact h
        · exact hout r hr
      generalize ha : a q = aq
      generalize hb : b q = bq
      fin_cases aq <;> fin_cases bq <;> simp_all
    · rw [if_neg hout]

/-- The logical-paper-bit-`0` projector is diagonal in the register basis. -/
theorem paperBitZeroProjectorAt_eq_diagonal (q : Q) :
    paperBitZeroProjectorAt q =
      Matrix.diagonal (fun x : Basis Q => if x q = 1 then (1 : ℂ) else 0) := by
  ext a b
  rw [paperBitZeroProjectorAt, embedQubit_apply_ite]
  by_cases hab : a = b
  · subst b
    rw [if_pos (fun _ _ ↦ rfl)]
    simp only [Matrix.diagonal_apply_eq]
    rw [bitZeroProjector_explicit]
    generalize ha : a q = aq
    fin_cases aq <;> simp_all
  · rw [Matrix.diagonal_apply_ne _ hab]
    by_cases hout : ∀ j, j ≠ q → a j = b j
    · rw [if_pos hout, bitZeroProjector_explicit]
      have hq : a q ≠ b q := by
        intro h
        apply hab
        funext r
        by_cases hr : r = q
        · subst r
          exact h
        · exact hout r hr
      generalize ha : a q = aq
      generalize hb : b q = bq
      fin_cases aq <;> fin_cases bq <;> simp_all
    · rw [if_neg hout]

/-- Project onto raw bit value `b` at coordinate `q`, acting identically elsewhere. -/
def coordinateProjector (q : Q) (b : QubitIndex) : Operator Q :=
  if b = 0 then paperBitOneProjectorAt q else paperBitZeroProjectorAt q

theorem coordinateProjector_eq_diagonal (q : Q) (b : QubitIndex) :
    coordinateProjector q b =
      Matrix.diagonal (fun x : Basis Q => if x q = b then (1 : ℂ) else 0) := by
  by_cases hb : b = 0
  · subst b
    simpa only [coordinateProjector, if_pos] using
      paperBitOneProjectorAt_eq_diagonal q
  · have hb1 : b = 1 := Fin.eq_one_of_ne_zero b hb
    subst b
    rw [coordinateProjector, if_neg (by decide)]
    exact paperBitZeroProjectorAt_eq_diagonal q

theorem coordinateProjector_mem_generated (q : Q) (b : QubitIndex) :
    coordinateProjector q b ∈ generated (Q := Q) := by
  rw [coordinateProjector]
  split_ifs
  · rw [paperBitOneProjectorAt_eq]
    exact (generated (Q := Q)).smul_mem
      ((generated (Q := Q)).add_mem
        (generated (Q := Q)).one_mem (zAt_mem_generated q)) _
  · rw [paperBitZeroProjectorAt_eq]
    exact (generated (Q := Q)).smul_mem
      ((generated (Q := Q)).sub_mem
        (generated (Q := Q)).one_mem (zAt_mem_generated q)) _

theorem coordinateProjector_commute (x : Basis Q) (q r : Q) :
    Commute (coordinateProjector q (x q)) (coordinateProjector r (x r)) := by
  rw [coordinateProjector_eq_diagonal, coordinateProjector_eq_diagonal]
  exact Matrix.commute_diagonal _ _

/-- Product of the coordinate projectors selecting the complete basis assignment `x`. -/
def basisProjector (x : Basis Q) : Operator Q :=
  Finset.univ.noncommProd (fun q => coordinateProjector q (x q))
    (fun q _ r _ _ => coordinateProjector_commute x q r)

theorem basisProjector_mem_generated (x : Basis Q) :
    basisProjector x ∈ generated (Q := Q) := by
  exact (generated (Q := Q)).toSubmonoid.noncommProd_mem Finset.univ
    (fun q => coordinateProjector q (x q))
    (fun q _ r _ _ => coordinateProjector_commute x q r)
    (fun q _ => coordinateProjector_mem_generated q (x q))

/-- The complete basis projector is the diagonal standard matrix unit at `x`. -/
theorem basisProjector_eq_single (x : Basis Q) :
    basisProjector x = Matrix.single x x 1 := by
  rw [basisProjector]
  let d : Q → Basis Q → ℂ :=
    fun q a => if a q = x q then 1 else 0
  have hcoord (q : Q) : coordinateProjector q (x q) = Matrix.diagonal (d q) := by
    exact coordinateProjector_eq_diagonal q (x q)
  rw [Finset.noncommProd_congr (s₂ := Finset.univ) rfl
    (fun q _ => hcoord q)]
  simp_rw [← Matrix.diagonalRingHom_apply]
  rw [← Finset.map_noncommProd Finset.univ d
    (fun _ _ _ _ _ => Commute.all _ _)
    (Matrix.diagonalRingHom (Basis Q) ℂ)]
  rw [Finset.noncommProd_eq_prod]
  rw [Matrix.diagonalRingHom_apply]
  ext a b
  by_cases hab : a = b
  · subst b
    simp only [Matrix.diagonal_apply_eq,
      Finset.prod_apply, d]
    by_cases hax : a = x
    · subst a
      simp [Matrix.single]
    · have hex : ∃ q, a q ≠ x q := by
        simpa only [Function.ne_iff] using hax
      obtain ⟨q, hq⟩ := hex
      rw [Finset.prod_eq_zero (Finset.mem_univ q)]
      · have hxa : x ≠ a := fun h => hax h.symm
        simp [Matrix.single, hxa]
      · simp [hq]
  · rw [Matrix.diagonal_apply_ne _ hab]
    have himp : x = a → x ≠ b := fun hxa hxb => hab (hxa.symm.trans hxb)
    simp [Matrix.single]
    exact himp

/-- Product of the commuting coordinate flips in `s`. -/
def flipProduct (s : Finset Q) : Equiv.Perm (Basis Q) :=
  s.noncommProd flipAt
    (fun _ _ _ _ h => flipAt_commute_of_ne h)

omit [Fintype Q] in
theorem flipProduct_apply (s : Finset Q) (a : Basis Q) (r : Q) :
    flipProduct s a r =
      if r ∈ s then Equiv.swap (0 : QubitIndex) 1 (a r) else a r := by
  induction s using Finset.induction_on generalizing a with
  | empty => simp [flipProduct, Finset.noncommProd_empty]
  | @insert q s hq ih =>
      rw [flipProduct, Finset.noncommProd_insert_of_notMem s q flipAt _ hq]
      rw [Equiv.Perm.mul_apply]
      have hih := ih a
      rw [flipProduct] at hih
      by_cases hrq : r = q
      · subst r
        rw [flipAt_apply_same, hih]
        simp [hq]
      · by_cases hrs : r ∈ s
        · rw [flipAt_apply_of_ne hrq, hih]
          simp [hrs, hrq]
        · rw [flipAt_apply_of_ne hrq, hih]
          simp [hrs, hrq]

def differingCoordinates (x y : Basis Q) : Finset Q :=
  Finset.univ.filter fun q => x q ≠ y q

/-- Product of embedded `X` operators at exactly the coordinates where `x` and `y` differ. -/
def basisFlip (x y : Basis Q) : Operator Q :=
  (differingCoordinates x y).noncommProd xAt
    (fun _ _ _ _ h => by
      apply (commute_iff_eq _ _).2
      simpa only [xAt] using embedQubit_commute_of_ne h pauliX pauliX)

theorem basisFlip_mem_generated (x y : Basis Q) :
    basisFlip x y ∈ generated (Q := Q) := by
  exact (generated (Q := Q)).toSubmonoid.noncommProd_mem
    (differingCoordinates x y) xAt
    (fun _ _ _ _ h => by
      apply (commute_iff_eq _ _).2
      simpa only [xAt] using embedQubit_commute_of_ne h pauliX pauliX)
    (fun q _ => xAt_mem_generated q)

theorem basisFlip_eq_permMatrix (x y : Basis Q) :
    basisFlip x y = (flipProduct (differingCoordinates x y))⁻¹.permMatrix ℂ := by
  rw [basisFlip, flipProduct]
  calc
    (differingCoordinates x y).noncommProd xAt _ =
        (differingCoordinates x y).noncommProd
          (fun q => (Matrix.permMatrixHom (R := ℂ)) (flipAt q)) _ := by
      apply Finset.noncommProd_congr rfl
      intro q _
      rw [Matrix.permMatrixHom_apply, flipAt_inv]
      exact xAt_eq_permMatrix q
    _ = (Matrix.permMatrixHom (R := ℂ))
          ((differingCoordinates x y).noncommProd flipAt
            (fun _ _ _ _ h => flipAt_commute_of_ne h)) := by
      symm
      apply Finset.map_noncommProd
    _ = ((differingCoordinates x y).noncommProd flipAt
          (fun _ _ _ _ h => flipAt_commute_of_ne h))⁻¹.permMatrix ℂ := by
      rw [Matrix.permMatrixHom_apply]

theorem flipProduct_differing_apply (x y : Basis Q) :
    flipProduct (differingCoordinates x y) y = x := by
  funext q
  rw [flipProduct_apply]
  by_cases hxy : x q = y q
  · rw [if_neg]
    · exact hxy.symm
    · simp [differingCoordinates, hxy]
  · rw [if_pos]
    · generalize hx : x q = xb
      generalize hy : y q = yb
      fin_cases xb <;> fin_cases yb <;> simp_all
    · simp [differingCoordinates, hxy]

theorem basisFlip_apply_pair (x y : Basis Q) : basisFlip x y x y = 1 := by
  rw [basisFlip_eq_permMatrix]
  simp only [Equiv.Perm.permMatrix, PEquiv.toMatrix_apply,
    Equiv.toPEquiv_apply, Option.mem_def, Option.some.injEq]
  have hcond : (flipProduct (differingCoordinates x y))⁻¹ x = y := by
    rw [Equiv.Perm.inv_def, Equiv.symm_apply_eq]
    exact (flipProduct_differing_apply x y).symm
  rw [if_pos hcond]

/-- Construct the standard matrix unit from two basis projectors and their transition flip. -/
def reconstructedMatrixUnit (x y : Basis Q) : Operator Q :=
  basisProjector x * basisFlip x y * basisProjector y

theorem reconstructedMatrixUnit_eq_single (x y : Basis Q) :
    reconstructedMatrixUnit x y = Matrix.single x y 1 := by
  rw [reconstructedMatrixUnit, basisProjector_eq_single,
    basisProjector_eq_single, Matrix.single_mul_mul_single,
    basisFlip_apply_pair]
  simp

/-- Every standard matrix unit belongs to the algebra generated by the initial descriptors. -/
theorem matrixUnit_mem_generated (x y : Basis Q) :
    Matrix.single x y 1 ∈ generated (Q := Q) := by
  rw [← reconstructedMatrixUnit_eq_single]
  exact (generated (Q := Q)).mul_mem
    ((generated (Q := Q)).mul_mem
      (basisProjector_mem_generated x) (basisFlip_mem_generated x y))
    (basisProjector_mem_generated y)

/-- Every global register operator belongs to the generated algebra. -/
theorem every_operator_mem_generated (A : Operator Q) :
    A ∈ generated (Q := Q) := by
  let b := Matrix.stdBasis ℂ (Basis Q) (Basis Q)
  rw [← Module.Basis.sum_repr b A]
  exact (generated (Q := Q)).sum_mem fun ij _ =>
    (generated (Q := Q)).smul_mem (by
      change Matrix.stdBasis ℂ (Basis Q) (Basis Q) ij ∈ generated (Q := Q)
      rw [Matrix.stdBasis_eq_single]
      exact matrixUnit_mem_generated ij.1 ij.2) _

/-- The constructively generated subalgebra is the full operator algebra. -/
theorem generated_eq_top : generated (Q := Q) = ⊤ := by
  ext A
  constructor
  · intro _
    trivial
  · intro _
    exact every_operator_mem_generated A

/-- Technical `xAt`/`zAt` range form of algebraic completeness. -/
theorem xAt_zAt_adjoin_eq_top :
    Algebra.adjoin ℂ (Set.range (xAt : Q → Operator Q) ∪ Set.range zAt) = ⊤ :=
  generated_eq_top

end
end Generation

noncomputable section

variable {Q : Type*} [Fintype Q] [DecidableEq Q]

private def evolutionAut (U : UnitaryOperator Q) : Operator Q ≃⋆ₐ[ℂ] Operator Q :=
  Unitary.conjStarAlgAut ℂ (Operator Q) (star U)

@[simp]
private theorem evolutionAut_apply (U : UnitaryOperator Q) (A : Operator Q) :
    evolutionAut U A = Register.heisenberg U A := by
  simp [evolutionAut, Unitary.conjStarAlgAut_apply, Register.heisenberg,
    Matrix.star_eq_conjTranspose]

/-- Evolving a family maps its component set through the unitary conjugation automorphism. -/
theorem components_evolve (U : UnitaryOperator Q) (D : DescriptorFamily Q) :
    components (evolve U D) = evolutionAut U '' components D := by
  ext A
  constructor
  · rintro ⟨⟨q, a⟩, rfl⟩
    refine ⟨(D q).component a, ⟨⟨q, a⟩, rfl⟩, ?_⟩
    dsimp only
    rw [evolve_apply, Descriptor.evolve_component, evolutionAut_apply]
  · rintro ⟨A, ⟨⟨q, a⟩, rfl⟩, rfl⟩
    refine ⟨⟨q, a⟩, ?_⟩
    dsimp only
    rw [evolve_apply, Descriptor.evolve_component, evolutionAut_apply]

/-- Unitary simultaneous evolution preserves algebraic completeness of a descriptor family. -/
theorem GeneratesOperatorAlgebra.evolve {D : DescriptorFamily Q}
    (hD : GeneratesOperatorAlgebra D) (U : UnitaryOperator Q) :
    GeneratesOperatorAlgebra (evolve U D) := by
  unfold GeneratesOperatorAlgebra
  rw [components_evolve]
  change Algebra.adjoin ℂ ((evolutionAut U).toAlgEquiv.toAlgHom '' components D) = ⊤
  rw [Algebra.adjoin_image, hD, Algebra.map_top]
  exact (AlgHom.range_eq_top _).2 (evolutionAut U).surjective

/-- The initial `X` and `Z` descriptor components generate every global register operator. -/
theorem initialXZ_generates_operator_algebra :
    Algebra.adjoin ℂ (initialXZComponents Q) = ⊤ :=
  Generation.generated_eq_top

/--
Algebraic completeness of the initial descriptor family: its components generate the full complex
operator algebra on the register.  In fact, the proof uses only its `X` and `Z` components.
-/
theorem initial_generates_operator_algebra :
    Algebra.adjoin ℂ (initialComponents Q) = ⊤ :=
  eq_top_mono
    (Algebra.adjoin_mono initialXZComponents_subset_initialComponents)
    initialXZ_generates_operator_algebra

/-- The initial descriptor family is algebraically complete. -/
theorem initial_generates : GeneratesOperatorAlgebra (initial Q) :=
  initial_generates_operator_algebra

/-- Every unitary evolution of the initial family remains algebraically complete. -/
theorem evolved_initial_generates (U : UnitaryOperator Q) :
    GeneratesOperatorAlgebra (evolve U (initial Q)) :=
  initial_generates.evolve U

end

end DescriptorFamily
end Deutsch
