import Deutsch.Gates.AxisRotation

/-!
# Arbitrary-axis rotations in named and current register frames

This module lifts the local arbitrary-axis rotation to a named qubit in a finite
register and then transports it through an arbitrary unitary Heisenberg frame.
The resulting current-frame gate is the genuine matrix exponential generated by
the current descriptor's axis operator.
-/

namespace Deutsch
namespace Gates

open Foundations Register
open NormedSpace
open scoped Matrix

noncomputable section

variable {Q : Type*} [Fintype Q] [DecidableEq Q]

/-! ## Named-register operators -/

/-- Embed the Pauli operator `v · σ` at the named register coordinate `q`. -/
def pauliVectorAt (q : Q) (v : Vector3) : Operator Q :=
  embedQubit q (pauliVector v)

/-- Embed the unit-axis Pauli operator `n · σ` at `q`. -/
def axisPauliAt (q : Q) (n : UnitAxis) : Operator Q :=
  pauliVectorAt q n.1

/-- The named-register generator `-i θ (n · σ_q) / 2`. -/
def axisRotationGeneratorAt (q : Q) (n : UnitAxis) (theta : ℝ) : Operator Q :=
  (-Complex.I * (theta / 2 : ℂ)) • axisPauliAt q n

/-- The local arbitrary-axis rotation embedded at the named coordinate `q`. -/
def axisRotationAt (q : Q) (n : UnitAxis) (theta : ℝ) : Operator Q :=
  embedQubit q (axisRotation n theta)

theorem pauliVectorAt_eq_components (q : Q) (v : Vector3) :
    pauliVectorAt q v =
      (v.x : ℂ) • xAt q + (v.y : ℂ) • yAt q + (v.z : ℂ) • zAt q := by
  rw [pauliVectorAt, pauliVector, embedQubit_add, embedQubit_add,
    embedQubit_smul, embedQubit_smul, embedQubit_smul]
  rfl

theorem axisPauliAt_eq_components (q : Q) (n : UnitAxis) :
    axisPauliAt q n =
      (n.1.x : ℂ) • xAt q + (n.1.y : ℂ) • yAt q +
        (n.1.z : ℂ) • zAt q := by
  exact pauliVectorAt_eq_components q n.1

theorem axisPauliAt_isHermitian (q : Q) (n : UnitAxis) :
    (axisPauliAt q n).IsHermitian := by
  rw [axisPauliAt, pauliVectorAt]
  exact embedQubit_isHermitian q (axisPauli n) (axisPauli_isHermitian n)

private theorem embedQubit_exp (q : Q) (A : QubitMatrix) :
    embedQubit q (exp A) = exp (embedQubit q A) := by
  open scoped Matrix.Norms.Operator in
    exact NormedSpace.map_exp (embedQubitAlgHom q)
      (embedQubitAlgHom q).toLinearMap.continuous_of_finiteDimensional A

theorem embedQubit_axisRotationGenerator (q : Q) (n : UnitAxis) (theta : ℝ) :
    embedQubit q (axisRotationGenerator n theta) =
      axisRotationGeneratorAt q n theta := by
  rw [axisRotationGenerator, axisRotationGeneratorAt, axisPauliAt,
    pauliVectorAt, axisPauli, embedQubit_smul]

/-- The named-register rotation is the genuine global matrix exponential of its generator. -/
theorem exp_axisRotationGeneratorAt (q : Q) (n : UnitAxis) (theta : ℝ) :
    exp (axisRotationGeneratorAt q n theta) = axisRotationAt q n theta := by
  rw [← embedQubit_axisRotationGenerator, ← embedQubit_exp,
    exp_axisRotationGenerator, axisRotationAt]

theorem axisRotationAt_unitary (q : Q) (n : UnitAxis) (theta : ℝ) :
    axisRotationAt q n theta ∈ Matrix.unitaryGroup (Basis Q) ℂ :=
  embedQubit_unitary q (axisRotation n theta) (axisRotation_isUnitary n theta)

theorem axisRotationAt_isSupportedOn (q : Q) (n : UnitAxis) (theta : ℝ) :
    IsSupportedOn {q} (axisRotationAt q n theta) :=
  embedQubit_isSupportedOn q (axisRotation n theta)

theorem axisRotationAt_conjTranspose (q : Q) (n : UnitAxis) (theta : ℝ) :
    (axisRotationAt q n theta)ᴴ = axisRotationAt q n (-theta) := by
  rw [axisRotationAt, embedQubit_conjTranspose, axisRotation_conjTranspose]
  rfl

theorem axisRotationAt_heisenberg (q : Q) (n : UnitAxis) (theta : ℝ)
    (v : Vector3) :
    Register.heisenberg (axisRotationAt q n theta) (pauliVectorAt q v) =
      pauliVectorAt q (Vector3.heisenbergRotate n.1 theta v) := by
  rw [axisRotationAt, pauliVectorAt, heisenberg_embedQubit,
    axisRotation_heisenberg, pauliVectorAt]

/-! ## Descriptor-axis operators -/

/-- The real Pauli vector `v · d` formed from a global descriptor triple. -/
def descriptorPauliVector (d : Descriptor Q) (v : Vector3) : Operator Q :=
  (v.x : ℂ) • d.x + (v.y : ℂ) • d.y + (v.z : ℂ) • d.z

/-- The unit-axis operator `n · d` formed from a global descriptor triple. -/
def descriptorAxisPauli (d : Descriptor Q) (n : UnitAxis) : Operator Q :=
  descriptorPauliVector d n.1

theorem descriptorPauliVector_initial (q : Q) (v : Vector3) :
    descriptorPauliVector (Descriptor.initial q) v = pauliVectorAt q v := by
  rw [descriptorPauliVector, pauliVectorAt_eq_components]
  rfl

theorem descriptorPauliVector_evolve (W : Operator Q) (d : Descriptor Q)
    (v : Vector3) :
    descriptorPauliVector (d.evolve W) v =
      Register.heisenberg W (descriptorPauliVector d v) := by
  rw [descriptorPauliVector, descriptorPauliVector,
    Register.heisenberg_add, Register.heisenberg_add,
    Register.heisenberg_smul, Register.heisenberg_smul,
    Register.heisenberg_smul]
  rfl

theorem descriptorAxisPauli_initial (q : Q) (n : UnitAxis) :
    descriptorAxisPauli (Descriptor.initial q) n = axisPauliAt q n := by
  exact descriptorPauliVector_initial q n.1

theorem descriptorAxisPauli_evolve (W : Operator Q) (d : Descriptor Q)
    (n : UnitAxis) :
    descriptorAxisPauli (d.evolve W) n =
      Register.heisenberg W (descriptorAxisPauli d n) := by
  exact descriptorPauliVector_evolve W d n.1

/-! ## Current-frame exponential and covariance -/

/-- The named qubit's axis operator after transport through the Heisenberg frame `W`. -/
def currentAxisPauli (W : Operator Q) (q : Q) (n : UnitAxis) : Operator Q :=
  descriptorAxisPauli ((Descriptor.initial q).evolve W) n

theorem currentAxisPauli_eq_components
    (W : Operator Q) (q : Q) (n : UnitAxis) :
    currentAxisPauli W q n =
      (n.1.x : ℂ) • ((Descriptor.initial q).evolve W).x +
        (n.1.y : ℂ) • ((Descriptor.initial q).evolve W).y +
        (n.1.z : ℂ) • ((Descriptor.initial q).evolve W).z :=
  rfl

/-- The current-frame generator `-i θ (n · q(t)) / 2`. -/
def currentAxisRotationGenerator (W : Operator Q) (q : Q) (n : UnitAxis)
    (theta : ℝ) : Operator Q :=
  (-Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n

/-- The actual matrix exponential generated by the current descriptor axis. -/
def currentAxisRotation (W : Operator Q) (q : Q) (n : UnitAxis)
    (theta : ℝ) : Operator Q :=
  exp (currentAxisRotationGenerator W q n theta)

theorem currentAxisPauli_eq_heisenberg (W : Operator Q) (q : Q) (n : UnitAxis) :
    currentAxisPauli W q n =
      Register.heisenberg W (axisPauliAt q n) := by
  rw [currentAxisPauli, descriptorAxisPauli_evolve,
    descriptorAxisPauli_initial]

theorem currentAxisRotationGenerator_eq_heisenberg
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) :
    currentAxisRotationGenerator W q n theta =
      Register.heisenberg W (axisRotationGeneratorAt q n theta) := by
  rw [currentAxisRotationGenerator, currentAxisPauli_eq_heisenberg,
    axisRotationGeneratorAt, Register.heisenberg_smul]

private theorem exp_heisenberg_of_unitary
    (W A : Operator Q)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    exp (Register.heisenberg W A) =
      Register.heisenberg W (exp A) := by
  let u : unitary (Operator Q) := ⟨W, hW⟩
  have h := Matrix.exp_units_conj' (Unitary.toUnits u) A
  simpa [Register.heisenberg, u, Matrix.star_eq_conjTranspose] using h

/-- The current exponential is exactly the shared-frame transport of the named local gate. -/
theorem currentAxisRotation_eq_heisenberg
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    currentAxisRotation W q n theta =
      Register.heisenberg W (axisRotationAt q n theta) := by
  rw [currentAxisRotation, currentAxisRotationGenerator_eq_heisenberg,
    exp_heisenberg_of_unitary W _ hW, exp_axisRotationGeneratorAt]

theorem currentAxisRotation_unitary
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    currentAxisRotation W q n theta ∈
      Matrix.unitaryGroup (Basis Q) ℂ := by
  rw [currentAxisRotation_eq_heisenberg W q n theta hW]
  exact Register.heisenberg_unitary W (axisRotationAt q n theta) hW
    (axisRotationAt_unitary q n theta)

private theorem currentAxisRotationGenerator_conjTranspose
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) :
    (currentAxisRotationGenerator W q n theta)ᴴ =
      (Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n := by
  rw [currentAxisRotationGenerator, Matrix.conjTranspose_smul]
  have haxis :
      (currentAxisPauli W q n).IsHermitian := by
    rw [currentAxisPauli_eq_heisenberg]
    exact Register.heisenberg_isHermitian W (axisPauliAt q n)
      (axisPauliAt_isHermitian q n)
  rw [haxis]
  congr 1
  apply Complex.ext <;> simp

/-- Equation-(17)-shaped current-frame conjugation, component by component.

Here `(Descriptor.initial q).evolve W` is the literal current descriptor `q(t)`, and
`currentAxisPauli W q n` is `n · q(t)`.
-/
theorem currentAxisRotation_heisenberg_component_exp
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) (a : Axis)
    (_hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    Register.heisenberg (currentAxisRotation W q n theta)
        (((Descriptor.initial q).evolve W).component a) =
      exp ((Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n) *
        ((Descriptor.initial q).evolve W).component a *
        exp ((-Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n) := by
  rw [Register.heisenberg, currentAxisRotation,
    ← Matrix.exp_conjTranspose,
    currentAxisRotationGenerator_conjTranspose]
  rfl

/-- The transported named gate has exactly Deutsch's current-descriptor exponential action. -/
theorem axisRotationAt_heisenberg_current_component_exp
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) (a : Axis)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    Register.heisenberg
        (Register.heisenberg W (axisRotationAt q n theta))
        (((Descriptor.initial q).evolve W).component a) =
      exp ((Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n) *
        ((Descriptor.initial q).evolve W).component a *
        exp ((-Complex.I * (theta / 2 : ℂ)) • currentAxisPauli W q n) := by
  rw [← currentAxisRotation_eq_heisenberg W q n theta hW]
  exact currentAxisRotation_heisenberg_component_exp W q n theta a hW

/-- Current-frame covariance of arbitrary Pauli-vector conjugation. -/
theorem currentAxisRotation_heisenberg_covariant
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) (v : Vector3)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    Register.heisenberg (currentAxisRotation W q n theta)
        (descriptorPauliVector ((Descriptor.initial q).evolve W) v) =
      Register.heisenberg W
        (Register.heisenberg (axisRotationAt q n theta) (pauliVectorAt q v)) := by
  rw [currentAxisRotation_eq_heisenberg W q n theta hW,
    descriptorPauliVector_evolve, descriptorPauliVector_initial]
  exact Register.heisenberg_covariance W (axisRotationAt q n theta)
    (pauliVectorAt q v) hW

/-- Rodrigues form of the exact current-frame arbitrary-axis rotation. -/
theorem currentAxisRotation_heisenberg
    (W : Operator Q) (q : Q) (n : UnitAxis) (theta : ℝ) (v : Vector3)
    (hW : W ∈ Matrix.unitaryGroup (Basis Q) ℂ) :
    Register.heisenberg (currentAxisRotation W q n theta)
        (descriptorPauliVector ((Descriptor.initial q).evolve W) v) =
      descriptorPauliVector ((Descriptor.initial q).evolve W)
        (Vector3.heisenbergRotate n.1 theta v) := by
  rw [currentAxisRotation_heisenberg_covariant W q n theta v hW,
    axisRotationAt_heisenberg, descriptorPauliVector_evolve,
    descriptorPauliVector_initial]

end
end Gates
end Deutsch
